"""
LLM-Generated PyReason Rules Example
Uses Claude to generate valid PyReason rules for a simple knowledge graph,
validates them with pr.Rule, and runs inference.

SETUP (Mac/Linux):
    export ANTHROPIC_API_KEY=your_key_here

SETUP (Windows PowerShell):
    $env:ANTHROPIC_API_KEY="your_key_here"

RUN:
  python examples/llm_generated_rules_ex.py
"""

import os
import sys
import anthropic
import pyreason as pr
import networkx as nx


# ================================ CREATE GRAPH ================================
g = nx.DiGraph()

# A Simple Student-Major-Department KG
g.add_edge('alice', 'math', major_in=1)
g.add_edge('bob',   'math', major_in=1)
g.add_edge('mary',  'cs',   major_in=1)

# Major -> Department
g.add_edge('math', 'math_dept', in_department=1)
g.add_edge('cs',   'cs_dept',   in_department=1)


# ================================ PROMPT ======================================
PROMPT = """\
Generate exactly 2 PyReason rules for this knowledge graph.

### Predicates in the graph
- major_in(Student, Major)         — e.g., major_in(alice, math)
- in_department(Major, Department) — e.g., in_department(math, math_dept)

### PyReason Rule Syntax
    head(X, Y) <-0 body1(...), body2(...)

- Use `<-0` (rule fires immediately) or `<-1` (fires after 1 timestep)
- Body predicates are separated by commas

### Variables are uppercase letters (X, Y, Z)

### Constraints
- Each rule must have exactly 2 body predicates
- Body predicates must share at least one variable (to create a meaningful join)
- Use only the predicates listed above in the body
- You may invent a new head predicate name

### Example (different graph, shows syntax only)
    grandparent(X, Y) <-0 parent(X, Z), parent(Z, Y)

### Output format
Output only the 2 rules, one per line. No markdown, no explanation, no numbering.
"""


# ================================ CALL CLAUDE ================================
if not os.environ.get("ANTHROPIC_API_KEY"):
    sys.exit("Error: set ANTHROPIC_API_KEY before running.")

client = anthropic.Anthropic()
response = client.messages.create(
    model="claude-sonnet-4-20250514",
    max_tokens=1024,
    messages=[{"role": "user", "content": PROMPT}],
)
rules = [line.strip() for line in response.content[0].text.splitlines() if line.strip()]

print("Rules generated by Claude:")
for r in rules:
    print(f"  {r}")


# ================================ VALIDATE ====================================
valid_rules = []
for rule_str in rules:
    try:
        pr.Rule(rule_str)
        valid_rules.append(rule_str)
        print(f"  [VALID]   {rule_str}")
    except Exception as e:
        print(f"  [INVALID] {rule_str}  Error: {e}")


# ================================ LOAD + REASON ==============================
pr.settings.verbose = False
pr.load_graph(g)

for i, rule_str in enumerate(valid_rules):
    pr.add_rule(pr.Rule(rule_str, name=f"rule_{i}", infer_edges=True))

interpretation = pr.reason(timesteps=2)


# ================================ VIEW RESULTS ===============================
head_predicates = [r.split("(")[0].strip() for r in valid_rules]
for df in pr.filter_and_sort_edges(interpretation, head_predicates):
    if not df.empty:
        print(df.to_string(index=False))